/**
 * Curated medication names for the creation wizard's autocomplete.
 *
 * Pure data, mirroring `country-data.ts`. Each entry is `[name, genericName]`;
 * a generic drug repeats itself, a brand points at its active ingredient so
 * duplicate-therapy detection can tell that Panadol and Paracetamol are the
 * same thing.
 *
 * This is a *convenience list*, not a formulary — it exists to normalise
 * spelling, not to advise. Nothing in the product reads it to make a clinical
 * judgement. Extend it freely; the seeder is idempotent on `name`.
 *
 * Brand names lean towards those common in the UK, US and Nigeria, matching
 * where the app's country list suggests users are.
 */
export type MedicationNameSeed = readonly [name: string, genericName: string];

export const MEDICATION_NAMES: readonly MedicationNameSeed[] = [
  // ── Analgesics & antipyretics ──────────────────────────────────────────
  ['Paracetamol', 'Paracetamol'],
  ['Acetaminophen', 'Paracetamol'],
  ['Panadol', 'Paracetamol'],
  ['Tylenol', 'Paracetamol'],
  ['Calpol', 'Paracetamol'],
  ['Ibuprofen', 'Ibuprofen'],
  ['Nurofen', 'Ibuprofen'],
  ['Advil', 'Ibuprofen'],
  ['Motrin', 'Ibuprofen'],
  ['Brufen', 'Ibuprofen'],
  ['Aspirin', 'Aspirin'],
  ['Naproxen', 'Naproxen'],
  ['Naprosyn', 'Naproxen'],
  ['Aleve', 'Naproxen'],
  ['Diclofenac', 'Diclofenac'],
  ['Voltaren', 'Diclofenac'],
  ['Cataflam', 'Diclofenac'],
  ['Celecoxib', 'Celecoxib'],
  ['Celebrex', 'Celecoxib'],
  ['Meloxicam', 'Meloxicam'],
  ['Mobic', 'Meloxicam'],
  ['Indomethacin', 'Indomethacin'],
  ['Ketorolac', 'Ketorolac'],
  ['Codeine', 'Codeine'],
  ['Co-codamol', 'Codeine/Paracetamol'],
  ['Tramadol', 'Tramadol'],
  ['Ultram', 'Tramadol'],
  ['Morphine', 'Morphine'],
  ['Oramorph', 'Morphine'],
  ['Oxycodone', 'Oxycodone'],
  ['OxyContin', 'Oxycodone'],
  ['Percocet', 'Oxycodone/Paracetamol'],
  ['Hydrocodone', 'Hydrocodone'],
  ['Fentanyl', 'Fentanyl'],
  ['Gabapentin', 'Gabapentin'],
  ['Neurontin', 'Gabapentin'],
  ['Pregabalin', 'Pregabalin'],
  ['Lyrica', 'Pregabalin'],
  ['Amitriptyline', 'Amitriptyline'],
  ['Sumatriptan', 'Sumatriptan'],
  ['Imigran', 'Sumatriptan'],
  ['Imitrex', 'Sumatriptan'],
  ['Rizatriptan', 'Rizatriptan'],
  ['Maxalt', 'Rizatriptan'],

  // ── Antibiotics & anti-infectives ──────────────────────────────────────
  ['Amoxicillin', 'Amoxicillin'],
  ['Amoxil', 'Amoxicillin'],
  ['Co-amoxiclav', 'Amoxicillin/Clavulanic acid'],
  ['Augmentin', 'Amoxicillin/Clavulanic acid'],
  ['Ampicillin', 'Ampicillin'],
  ['Penicillin V', 'Phenoxymethylpenicillin'],
  ['Flucloxacillin', 'Flucloxacillin'],
  ['Azithromycin', 'Azithromycin'],
  ['Zithromax', 'Azithromycin'],
  ['Clarithromycin', 'Clarithromycin'],
  ['Klaricid', 'Clarithromycin'],
  ['Erythromycin', 'Erythromycin'],
  ['Doxycycline', 'Doxycycline'],
  ['Vibramycin', 'Doxycycline'],
  ['Tetracycline', 'Tetracycline'],
  ['Ciprofloxacin', 'Ciprofloxacin'],
  ['Cipro', 'Ciprofloxacin'],
  ['Levofloxacin', 'Levofloxacin'],
  ['Ofloxacin', 'Ofloxacin'],
  ['Cephalexin', 'Cephalexin'],
  ['Keflex', 'Cephalexin'],
  ['Cefuroxime', 'Cefuroxime'],
  ['Ceftriaxone', 'Ceftriaxone'],
  ['Cefixime', 'Cefixime'],
  ['Metronidazole', 'Metronidazole'],
  ['Flagyl', 'Metronidazole'],
  ['Trimethoprim', 'Trimethoprim'],
  ['Co-trimoxazole', 'Trimethoprim/Sulfamethoxazole'],
  ['Bactrim', 'Trimethoprim/Sulfamethoxazole'],
  ['Septrin', 'Trimethoprim/Sulfamethoxazole'],
  ['Nitrofurantoin', 'Nitrofurantoin'],
  ['Clindamycin', 'Clindamycin'],
  ['Vancomycin', 'Vancomycin'],
  ['Gentamicin', 'Gentamicin'],
  ['Rifampicin', 'Rifampicin'],
  ['Isoniazid', 'Isoniazid'],
  ['Ethambutol', 'Ethambutol'],
  ['Pyrazinamide', 'Pyrazinamide'],
  ['Fluconazole', 'Fluconazole'],
  ['Diflucan', 'Fluconazole'],
  ['Ketoconazole', 'Ketoconazole'],
  ['Nystatin', 'Nystatin'],
  ['Terbinafine', 'Terbinafine'],
  ['Aciclovir', 'Aciclovir'],
  ['Acyclovir', 'Aciclovir'],
  ['Zovirax', 'Aciclovir'],
  ['Valaciclovir', 'Valaciclovir'],
  ['Oseltamivir', 'Oseltamivir'],
  ['Tamiflu', 'Oseltamivir'],

  // ── Antimalarials ──────────────────────────────────────────────────────
  ['Artemether/Lumefantrine', 'Artemether/Lumefantrine'],
  ['Coartem', 'Artemether/Lumefantrine'],
  ['Lonart', 'Artemether/Lumefantrine'],
  ['Artesunate', 'Artesunate'],
  ['Chloroquine', 'Chloroquine'],
  ['Hydroxychloroquine', 'Hydroxychloroquine'],
  ['Plaquenil', 'Hydroxychloroquine'],
  ['Quinine', 'Quinine'],
  ['Atovaquone/Proguanil', 'Atovaquone/Proguanil'],
  ['Malarone', 'Atovaquone/Proguanil'],
  ['Mefloquine', 'Mefloquine'],
  ['Primaquine', 'Primaquine'],
  ['Sulfadoxine/Pyrimethamine', 'Sulfadoxine/Pyrimethamine'],
  ['Fansidar', 'Sulfadoxine/Pyrimethamine'],

  // ── Cardiovascular ─────────────────────────────────────────────────────
  ['Amlodipine', 'Amlodipine'],
  ['Norvasc', 'Amlodipine'],
  ['Nifedipine', 'Nifedipine'],
  ['Adalat', 'Nifedipine'],
  ['Diltiazem', 'Diltiazem'],
  ['Verapamil', 'Verapamil'],
  ['Lisinopril', 'Lisinopril'],
  ['Zestril', 'Lisinopril'],
  ['Ramipril', 'Ramipril'],
  ['Enalapril', 'Enalapril'],
  ['Perindopril', 'Perindopril'],
  ['Captopril', 'Captopril'],
  ['Losartan', 'Losartan'],
  ['Cozaar', 'Losartan'],
  ['Valsartan', 'Valsartan'],
  ['Irbesartan', 'Irbesartan'],
  ['Candesartan', 'Candesartan'],
  ['Telmisartan', 'Telmisartan'],
  ['Atenolol', 'Atenolol'],
  ['Bisoprolol', 'Bisoprolol'],
  ['Metoprolol', 'Metoprolol'],
  ['Propranolol', 'Propranolol'],
  ['Carvedilol', 'Carvedilol'],
  ['Labetalol', 'Labetalol'],
  ['Bendroflumethiazide', 'Bendroflumethiazide'],
  ['Hydrochlorothiazide', 'Hydrochlorothiazide'],
  ['Indapamide', 'Indapamide'],
  ['Furosemide', 'Furosemide'],
  ['Lasix', 'Furosemide'],
  ['Spironolactone', 'Spironolactone'],
  ['Aldactone', 'Spironolactone'],
  ['Digoxin', 'Digoxin'],
  ['Atorvastatin', 'Atorvastatin'],
  ['Lipitor', 'Atorvastatin'],
  ['Simvastatin', 'Simvastatin'],
  ['Zocor', 'Simvastatin'],
  ['Rosuvastatin', 'Rosuvastatin'],
  ['Crestor', 'Rosuvastatin'],
  ['Pravastatin', 'Pravastatin'],
  ['Ezetimibe', 'Ezetimibe'],
  ['Fenofibrate', 'Fenofibrate'],
  ['Clopidogrel', 'Clopidogrel'],
  ['Plavix', 'Clopidogrel'],
  ['Warfarin', 'Warfarin'],
  ['Rivaroxaban', 'Rivaroxaban'],
  ['Xarelto', 'Rivaroxaban'],
  ['Apixaban', 'Apixaban'],
  ['Eliquis', 'Apixaban'],
  ['Dabigatran', 'Dabigatran'],
  ['Enoxaparin', 'Enoxaparin'],
  ['Clexane', 'Enoxaparin'],
  ['Isosorbide mononitrate', 'Isosorbide mononitrate'],
  ['Glyceryl trinitrate', 'Glyceryl trinitrate'],
  ['Ivabradine', 'Ivabradine'],

  // ── Diabetes & endocrine ───────────────────────────────────────────────
  ['Metformin', 'Metformin'],
  ['Glucophage', 'Metformin'],
  ['Gliclazide', 'Gliclazide'],
  ['Glibenclamide', 'Glibenclamide'],
  ['Glimepiride', 'Glimepiride'],
  ['Sitagliptin', 'Sitagliptin'],
  ['Januvia', 'Sitagliptin'],
  ['Linagliptin', 'Linagliptin'],
  ['Empagliflozin', 'Empagliflozin'],
  ['Jardiance', 'Empagliflozin'],
  ['Dapagliflozin', 'Dapagliflozin'],
  ['Forxiga', 'Dapagliflozin'],
  ['Pioglitazone', 'Pioglitazone'],
  ['Insulin glargine', 'Insulin glargine'],
  ['Lantus', 'Insulin glargine'],
  ['Insulin aspart', 'Insulin aspart'],
  ['NovoRapid', 'Insulin aspart'],
  ['Humalog', 'Insulin lispro'],
  ['Insulin lispro', 'Insulin lispro'],
  ['Mixtard', 'Insulin (biphasic)'],
  ['Semaglutide', 'Semaglutide'],
  ['Ozempic', 'Semaglutide'],
  ['Wegovy', 'Semaglutide'],
  ['Liraglutide', 'Liraglutide'],
  ['Levothyroxine', 'Levothyroxine'],
  ['Eltroxin', 'Levothyroxine'],
  ['Synthroid', 'Levothyroxine'],
  ['Carbimazole', 'Carbimazole'],
  ['Propylthiouracil', 'Propylthiouracil'],
  ['Prednisolone', 'Prednisolone'],
  ['Prednisone', 'Prednisone'],
  ['Dexamethasone', 'Dexamethasone'],
  ['Hydrocortisone', 'Hydrocortisone'],
  ['Fludrocortisone', 'Fludrocortisone'],
  ['Alendronic acid', 'Alendronic acid'],
  ['Fosamax', 'Alendronic acid'],
  ['Calcium/Vitamin D', 'Calcium/Colecalciferol'],
  ['Colecalciferol', 'Colecalciferol'],
  ['Vitamin D3', 'Colecalciferol'],

  // ── Respiratory & allergy ──────────────────────────────────────────────
  ['Salbutamol', 'Salbutamol'],
  ['Ventolin', 'Salbutamol'],
  ['Albuterol', 'Salbutamol'],
  ['Terbutaline', 'Terbutaline'],
  ['Salmeterol', 'Salmeterol'],
  ['Formoterol', 'Formoterol'],
  ['Beclometasone', 'Beclometasone'],
  ['Clenil', 'Beclometasone'],
  ['Budesonide', 'Budesonide'],
  ['Fluticasone', 'Fluticasone'],
  ['Flixotide', 'Fluticasone'],
  ['Seretide', 'Fluticasone/Salmeterol'],
  ['Symbicort', 'Budesonide/Formoterol'],
  ['Tiotropium', 'Tiotropium'],
  ['Spiriva', 'Tiotropium'],
  ['Ipratropium', 'Ipratropium'],
  ['Montelukast', 'Montelukast'],
  ['Singulair', 'Montelukast'],
  ['Theophylline', 'Theophylline'],
  ['Cetirizine', 'Cetirizine'],
  ['Zyrtec', 'Cetirizine'],
  ['Loratadine', 'Loratadine'],
  ['Claritin', 'Loratadine'],
  ['Fexofenadine', 'Fexofenadine'],
  ['Chlorphenamine', 'Chlorphenamine'],
  ['Piriton', 'Chlorphenamine'],
  ['Promethazine', 'Promethazine'],
  ['Phenergan', 'Promethazine'],

  // ── Gastrointestinal ───────────────────────────────────────────────────
  ['Omeprazole', 'Omeprazole'],
  ['Losec', 'Omeprazole'],
  ['Prilosec', 'Omeprazole'],
  ['Lansoprazole', 'Lansoprazole'],
  ['Pantoprazole', 'Pantoprazole'],
  ['Esomeprazole', 'Esomeprazole'],
  ['Nexium', 'Esomeprazole'],
  ['Ranitidine', 'Ranitidine'],
  ['Famotidine', 'Famotidine'],
  ['Gaviscon', 'Alginate/Antacid'],
  ['Metoclopramide', 'Metoclopramide'],
  ['Domperidone', 'Domperidone'],
  ['Ondansetron', 'Ondansetron'],
  ['Zofran', 'Ondansetron'],
  ['Loperamide', 'Loperamide'],
  ['Imodium', 'Loperamide'],
  ['Senna', 'Senna'],
  ['Lactulose', 'Lactulose'],
  ['Movicol', 'Macrogol'],
  ['Bisacodyl', 'Bisacodyl'],
  ['Mebeverine', 'Mebeverine'],
  ['Hyoscine butylbromide', 'Hyoscine butylbromide'],
  ['Buscopan', 'Hyoscine butylbromide'],
  ['Mesalazine', 'Mesalazine'],
  ['Oral rehydration salts', 'Oral rehydration salts'],

  // ── Mental health & neurology ──────────────────────────────────────────
  ['Sertraline', 'Sertraline'],
  ['Zoloft', 'Sertraline'],
  ['Fluoxetine', 'Fluoxetine'],
  ['Prozac', 'Fluoxetine'],
  ['Citalopram', 'Citalopram'],
  ['Escitalopram', 'Escitalopram'],
  ['Lexapro', 'Escitalopram'],
  ['Paroxetine', 'Paroxetine'],
  ['Venlafaxine', 'Venlafaxine'],
  ['Duloxetine', 'Duloxetine'],
  ['Mirtazapine', 'Mirtazapine'],
  ['Bupropion', 'Bupropion'],
  ['Trazodone', 'Trazodone'],
  ['Nortriptyline', 'Nortriptyline'],
  ['Diazepam', 'Diazepam'],
  ['Valium', 'Diazepam'],
  ['Lorazepam', 'Lorazepam'],
  ['Clonazepam', 'Clonazepam'],
  ['Alprazolam', 'Alprazolam'],
  ['Xanax', 'Alprazolam'],
  ['Zopiclone', 'Zopiclone'],
  ['Zolpidem', 'Zolpidem'],
  ['Melatonin', 'Melatonin'],
  ['Quetiapine', 'Quetiapine'],
  ['Seroquel', 'Quetiapine'],
  ['Olanzapine', 'Olanzapine'],
  ['Risperidone', 'Risperidone'],
  ['Aripiprazole', 'Aripiprazole'],
  ['Haloperidol', 'Haloperidol'],
  ['Lithium carbonate', 'Lithium carbonate'],
  ['Lamotrigine', 'Lamotrigine'],
  ['Sodium valproate', 'Sodium valproate'],
  ['Epilim', 'Sodium valproate'],
  ['Carbamazepine', 'Carbamazepine'],
  ['Tegretol', 'Carbamazepine'],
  ['Levetiracetam', 'Levetiracetam'],
  ['Keppra', 'Levetiracetam'],
  ['Phenytoin', 'Phenytoin'],
  ['Phenobarbital', 'Phenobarbital'],
  ['Topiramate', 'Topiramate'],
  ['Methylphenidate', 'Methylphenidate'],
  ['Ritalin', 'Methylphenidate'],
  ['Concerta', 'Methylphenidate'],
  ['Lisdexamfetamine', 'Lisdexamfetamine'],
  ['Elvanse', 'Lisdexamfetamine'],
  ['Vyvanse', 'Lisdexamfetamine'],
  ['Atomoxetine', 'Atomoxetine'],
  ['Donepezil', 'Donepezil'],
  ['Memantine', 'Memantine'],
  ['Levodopa/Carbidopa', 'Levodopa/Carbidopa'],
  ['Sinemet', 'Levodopa/Carbidopa'],
  ['Ropinirole', 'Ropinirole'],

  // ── Urology, sexual & reproductive health ──────────────────────────────
  ['Tamsulosin', 'Tamsulosin'],
  ['Finasteride', 'Finasteride'],
  ['Sildenafil', 'Sildenafil'],
  ['Viagra', 'Sildenafil'],
  ['Tadalafil', 'Tadalafil'],
  ['Cialis', 'Tadalafil'],
  ['Oxybutynin', 'Oxybutynin'],
  ['Solifenacin', 'Solifenacin'],
  ['Levonorgestrel/Ethinylestradiol', 'Levonorgestrel/Ethinylestradiol'],
  ['Microgynon', 'Levonorgestrel/Ethinylestradiol'],
  ['Rigevidon', 'Levonorgestrel/Ethinylestradiol'],
  ['Yasmin', 'Drospirenone/Ethinylestradiol'],
  ['Cerazette', 'Desogestrel'],
  ['Desogestrel', 'Desogestrel'],
  ['Norethisterone', 'Norethisterone'],
  ['Medroxyprogesterone', 'Medroxyprogesterone'],
  ['Estradiol', 'Estradiol'],
  ['Clomifene', 'Clomifene'],
  ['Folic acid', 'Folic acid'],
  ['Ferrous sulfate', 'Ferrous sulfate'],
  ['Ferrous fumarate', 'Ferrous fumarate'],
  ['Pregnacare', 'Prenatal multivitamin'],

  // ── Other common ───────────────────────────────────────────────────────
  ['Allopurinol', 'Allopurinol'],
  ['Colchicine', 'Colchicine'],
  ['Methotrexate', 'Methotrexate'],
  ['Azathioprine', 'Azathioprine'],
  ['Ciclosporin', 'Ciclosporin'],
  ['Tacrolimus', 'Tacrolimus'],
  ['Mycophenolate', 'Mycophenolate'],
  ['Hydroxyzine', 'Hydroxyzine'],
  ['Cyclizine', 'Cyclizine'],
  ['Betahistine', 'Betahistine'],
  ['Cinnarizine', 'Cinnarizine'],
  ['Multivitamin', 'Multivitamin'],
  ['Vitamin B12', 'Cyanocobalamin'],
  ['Cyanocobalamin', 'Cyanocobalamin'],
  ['Thiamine', 'Thiamine'],
  ['Zinc sulfate', 'Zinc sulfate'],
  ['Magnesium', 'Magnesium'],
  ['Omega-3', 'Omega-3 fatty acids'],
  ['Hydroxyurea', 'Hydroxycarbamide'],
  ['Hydroxycarbamide', 'Hydroxycarbamide'],
  ['Penicillamine', 'Penicillamine'],
  ['Tranexamic acid', 'Tranexamic acid'],
  ['Vitamin C', 'Ascorbic acid'],
  ['Ascorbic acid', 'Ascorbic acid'],
] as const;
